[runner]
seed = 42
total_episodes = 1
folder = "small_middle_late"
agent = "RandomAgent"

[scheduler]
running_time = 270

[job]
model = "ConvNet"
dataset = "cifar10"

[agent]
vocab = "models"
device = 0
gamma = 0.99
alpha = 0.01
hidden_size = 50
embedding_size = 16
final_weight = 0.5
