[runner]
seed = 42
total_episodes = 2
folder = "test2"
agent = "Agent"
desc = "Use this script to check any changes to training/agent"

[scheduler]
running_time = 70
gpu_changes = [{ time = 0, change = "up" }]

[job]
model = "ConvNet"
dataset = "cifar10"

[trainer]
weights = "results/small_early/weights.pth"
runtimes = "results/small_early/runtimes"

[agent]
vocab = "models"
device = 0
gamma = 0.99
alpha = 0.01
hidden_size = 50
embedding_size = 16
final_weight = 0.5
