[runner]
seed = 42
total_episodes = 15000
folder = "test_late6"
agent = "Agent"

[scheduler]
running_time = 400
gpu_changes = [{ time = 387, change = "up" }]
start_time = 387

[job]
model = "ConvNet"
dataset = "cifar10"

[agent]
vocab = "models"
device = 0
alpha = 0.0001
hidden_size = 50
embedding_size = 16
max_actions = 5
decider_lstm_size = 16
decider_linear_size = 128
learning_rate_decay = 0.99
time_encoding_size = 8
