[runner]
seed = 42
total_episodes = 1
folder = "test3"
agent = "RandomAgent"

[scheduler]
running_time = 26
gpu_changes = [{ time = 13, change = "up" }]

[job]
model = "ConvNet"
dataset = "cifar10"

[agent]
device = 1
gamma = 0.99
alpha = 0.01
hidden_size = 50
embedding_size = 16
final_weight = 0.5
