[runner]
seed = 42
total_episodes = 10
folder = "baseline_early"
agent = "RandomAgent"

[scheduler]
running_time = 330
gpu_changes = [{ time = 0, change = "up" }]

[trainer]
weights = "results/small_early/weights.pth"
runtimes = "results/small_early/runtimes"

[job]
model = "ConvNet"
dataset = "cifar10"

[agent]
vocab = "models"
device = 0
gamma = 0.99
alpha = 0.01
hidden_size = 50
embedding_size = 16
final_weight = 0.5
