[runner]
seed = 42
total_episodes = 10
folder = "baseline_middle"
agent = "RandomAgent"

[scheduler]
running_time = 200
gpu_changes = [{ time = 0, change = "up" }]

[trainer]
weights = "results/small_middle/weights.pth"
runtimes = "results/small_middle/runtimes"

[job]
model = "ConvNet"
dataset = "cifar10"

[agent]
vocab = "models"
device = 1
gamma = 0.99
alpha = 0.01
hidden_size = 50
embedding_size = 16
final_weight = 0.5
