[runner]
seed = 42
total_episodes = 10
folder = "baseline"
agent = "RandomAgent"

[scheduler]
running_time = 400
gpu_changes = [{ time = 200, change = "up" }]

[job]
model = "ConvNet"
dataset = "cifar10"

[agent]
device = 0
gamma = 0.99
alpha = 0.01
hidden_size = 50
embedding_size = 16
final_weight = 0.5
