[runner]
seed = 42
total_episodes = 10
folder = "baseline_early2"
agent = "RandomAgent"

[scheduler]
running_time = 400
gpu_changes = [{ time = 70, change = "up" }, { time = 110, change = "down" }]
start_time = 70

[trainer]
weights = "results/small_early2/weights.pth"
runtimes = "results/small_early2/runtimes"

[job]
model = "ConvNet2"
dataset = "cifar10"

[agent]
device = 0
