model = "imagenet_inception"
optimizer_args = { lr = 0.01 }
dataset = "cifar10"
epochs = 2
folder = "TestEnvironment"
desc = "Simple environment just to make sure we can train a network on a dataset"
[scaleupepochs]
1 = { modifier = "deepen", ignore = "inception_ignoreset", modify = "deepen_inception" }
