model = "cifar10_inception"
optimizer_args = { lr = 0.01 }
dataset = "cifar10"
epochs = 26
folder = "AdaptedInceptionCIFAR10_11_18_3"
desc = "Experiment where we train adapted InceptionNet from briefly trained teacher on CIFAR-10"
model_weights = "../results/TeacherInceptionCIFAR10_11_18_1/model4.pth" 
[scaleupepochs]
0 = { modifier = "deepen_blocks", filter_function = "inception_deepen_filter_function", add_batch_norm = true }

