model = "cifar10_inception"
optimizer_args = { lr = 0.01 }
dataset = "cifar10"
epochs = 22
folder = "AdaptedInceptionCIFAR10_11_18_5"
desc = "Experiment where we train adapted InceptionNet from briefly trained teacher on CIFAR-10 and then scale down using kd and wd"
model_weights = "../results/AdaptedInceptionCIFAR10_11_18_3/model4.pth" 
scaledownepochs = [0]


