model = "cifar10_inception"
optimizer_args = { lr = 0.01 }
dataset = "cifar10"
epochs = 25
folder = "TeacherInceptionCIFAR10_11_18_3a"
desc = "Experiment where we train InceptionNet briefly on CIFAR-10"

