model = "cifar10_inception"
optimizer_args = { lr = 0.01 }
dataset = "cifar10"
epochs = 13
folder = "TeacherInceptionCIFAR105"
desc = "Experiment where we train InceptionNet on CIFAR-10 as the teacher"