model = "cifar10_inception"
optimizer_args = { lr = 0.01 }
dataset = "cifar10"
epochs = 9
folder = "AdaptedInceptionCIFAR109"
desc = "Experiment where we train adapted InceptionNet from briefly trained teacher on CIFAR-10 and then downsize without weight distillation"
model_weights = "../results/TeacherInceptionCIFAR105/model4.pth" 
[scaleupepochs]
0 = { modifier = "random_deepen", ignore = "inception_ignoreset", modify = "deepen_inception" }

