model = "cifar10_inception"
optimizer_args = { lr = 0.01 }
dataset = "cifar10"
epochs = 50
folder = "BigInceptionCIFAR10_11_11_2"
desc = "Experiment where we train randomly deepened InceptionNet briefly on CIFAR10"
[scaleupepochs]
0 = { modifier = "random_deepen", ignore = "inception_ignoreset", modify = "deepen_inception" }

