model = "cifar10_inception"
optimizer_args = { lr = 0.01 }
dataset = "cifar10"
epochs = 17
folder = "AdaptedInceptionCIFAR10_11_20_3b"
desc = "Experiment where we train adapted InceptionNet from briefly trained teacher on CIFAR-10 and then scale down using wd"
model_weights = "../results/AdaptedInceptionCIFAR10_11_20_2a/model_after_4_epochs.pt" 
scaledownepochs = [0]
knowledge_distillation = false


