model = "SmallFeedForward"
model_args = { in_features = 784, out_features = 10 }
optimizer_args = { lr = 0.01 }
dataset = "mnist"
epochs = 5
folder = "TestEnvironment"
desc = "Simple environment just to make sure we can train a network on a dataset"