model = "cifar10_inception"
optimizer_args = { lr = 0.01 }
dataset = "cifar10"
epochs = 14
folder = "AdaptedInceptionCIFAR101104"
desc = "Experiment where we train adapted InceptionNet from briefly trained teacher on CIFAR-10 and then scale down using just kd"
model_weights = "../results/TeacherInceptionCIFAR10118/model4.pth" 
scaledownepochs = [4]
weight_distillation = false
[scaleupepochs]
0 = { modifier = "deepen", ignore = "inception_ignoreset", modify = "deepen_inception" }

