model = "cifar10_inception"
optimizer_args = { lr = 0.01 }
dataset = "cifar10"
epochs = 46
folder = "AdaptedInceptionCIFAR10_11_11_3"
desc = "Experiment where we train adapted InceptionNet from briefly trained teacher on CIFAR-10"
model_weights = "../results/TeacherInceptionCIFAR10_11_11_1/model4.pth" 
[scaleupepochs]
0 = { modifier = "deepen", ignore = "inception_ignoreset", modify = "deepen_inception" }

