model = "cifar10_inception"
optimizer_args = { lr = 0.001 }
dataset = "cifar10"
epochs = 21
folder = "AdaptedInceptionCIFAR10_11_20_2b"
desc = "Experiment where we train randomly adapted InceptionNet from briefly trained teacher on CIFAR-10"
model_weights = "../results/TeacherInceptionCIFAR10_11_20_1a/model_after_4_epochs.pt" 
[scaleupepochs]
0 = { modifier = "random_deepen_blocks", filter_function = "inception_deepen_filter_function", add_batch_norm = true }

