model = "cifar10_inception"
optimizer_args = { lr = 0.01 }
dataset = "cifar10"
epochs = 11
folder = "AdaptedInceptionCIFAR103"
desc = "Experiment where we train adapted InceptionNet from briefly trained teacher on CIFAR-10"
model_weights = "../results/BriefTeacherInceptionCIFAR102/model.pt"
[scaleupepochs]
0 = { modifier = "deepen", ignore = "inception_ignoreset", modify = "deepen_inception" }
