model = "cifar10_inception"
optimizer_args = { lr = 0.01 }
dataset = "cifar10"
epochs = 30
folder = "TeacherInceptionCIFAR10_11_18_1"
desc = "Experiment where we train InceptionNet briefly on CIFAR-10"

