[runner]
seed = 42
total_episodes = 50
folder = "late2"
agent = "Agent"

[scheduler]
running_time = 70
gpu_changes = [{ time = 0, change = "up" }]
start_time = 330

[trainer]
weights = "results/small_late/weights.pth"
runtimes = "results/small_late/runtimes"

[job]
model = "ConvNet"
dataset = "cifar10"

[agent]
vocab = "models"
device = 0
gamma = 0.99
alpha = 0.01
hidden_size = 50
embedding_size = 16
final_weight = 0.9
