[runner]
seed = 42
total_episodes = 10
folder = "baseline_early_middle3"
agent = "RandomAgent"

[scheduler]
running_time = 400
gpu_changes = [{ time = 140, change = "up" }, { time = 180, change = "down" }]
start_time = 140

[trainer]
weights = "results/small_early_middle3/weights.pth"
runtimes = "results/small_early_middle3/runtimes"

[job]
model = "ConvNet3"
dataset = "cifar10"

[agent]
device = 1
